# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.5
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: dlp14developing@gmail.com
author_name: Daniel Pointon
contract_name: ch_ai_n
preset_name: production
project_name: ch_ai_n

